#!/bin/bash

# Copyright 2012-2013 Bjorn Fahller <bjorn@fahller.se>
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

program=$1
shift
dir=$(mktemp -d /tmp/crpcutXXXXXX)
CRPCUT_TEXT_DECORATION=$'
</span>
BLOCKED=<span style="color:#d338d3">
PASSED=<span style="color:#009900">
FAILED=<span style="color:#cc0000">
NCFAILED=<span style="color:#adad27">
PASSED_SUM=<span style="color:#ffffff;background-color:#009900;font-weight:bold">
FAILED_SUM=<span style="color:#ffffff;background-color:#cc0000;font-weight:bold">
BLOCKED_SUM=<span style="color:#ffffff;background-color:#d338d3;font-weight:bold">
'
export CRPCUT_TEXT_DECORATION
echo "<html><pre>"
$program -d $dir $* | sed 's:^:    :1'
rv=$?
echo "</pre></html>"
rm -rf $dir
exit $rv
